Make a /etc/gitconfig.d directory.
As explained in the comment, this is to slice the knot of makechrootpkg
insisting on pre-filling in /etc/gitconfig to workaround git security
rules, which would mean we otherwise could not config-manage that file.

diff --git a/kousu-desktop/arch-conf.install b/kousu-desktop/arch-conf.install
--- a/kousu-desktop/arch-conf.install
+++ b/kousu-desktop/arch-conf.install
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 post_upgrade() {
   # https://wiki.archlinux.org/title/Installation_guide#Time_zone
   timedatectl set-ntp true # XXX should probably...wait until ntp actually syncs before running the next command?
@@ -67,6 +69,16 @@ EOF
 # as far as etckeeper is concerned
 .updated
 EOF
+
+    if ! [ -f /etc/sudoers.d/builduser-pacman ]; then
+      # **during a makechrootpkg build** don't track gitconfig.
+      # this is entirely because makechrootpkg also wants
+      # to edit that file
+      cat >> /etc/.gitignore <<EOF
+/gitconfig
+EOF
+    fi
+
       etckeeper init # assumption: this is idempotent
       etckeeper vcs config user.name root  # etckeeper gets mad without this.
 
@@ -90,6 +102,17 @@ EOF
   # This is like ansible's `lineinfile:` with all the pain that entails.
   sed -i '/sshd_config.d/d' /etc/ssh/sshd_config # get rid of any pre-existing lines
   echo 'Include /etc/ssh/sshd_config.d/*.conf' >> /etc/ssh/sshd_config
+
+  # force git to use a .d directory
+  # Useful in general, but particularly because makechrootpkg(1)
+  # injects its own /etc/gitconfig which means downstream package
+  # fails to build when building with that method.
+  if ! grep -q '/etc/gitconfig.d/00-defaults.conf' /etc/gitconfig 2>/dev/null; then
+      cat << EOF | tee -a /etc/gitconfig
+[include]
+    path = /etc/gitconfig.d/00-defaults.conf
+EOF
+  fi
 
   systemctl enable reflector.timer
   systemctl enable reflector.service
